### ISSUE TITLE
Change assets paths to relative.

### ISSUE THREAD

**Issue by tmwh** [jetthoughts/oauth2-me#2]
Absolute paths wont work for users forks, for example:
http://tmwh.github.io/oauth2-me/

https://github.com/jetthoughts/oauth2-me/blob/gh-pages/index.html#L5
https://github.com/jetthoughts/oauth2-me/blob/gh-pages/redirect/index.html#L4-L6

**Comment by NazarKY** [comment]
have fixed in #1 - but haven't  merged.  Close when will merge #1  with master. 
[verify](http://staging.nazarky-oauth2me.divshot.io/)
